### ISSUE TITLE
No instruction counts when you exit the program with syscall 10 

### ISSUE THREAD

**Issue by weiwenzhou** [sbustars/STARS#2]
OS: Windows
Ran in: Git Bash and Windows Powershell

While the instruction counts show up when you run a file without syscall 10, 
adding li $v0, 10 \n syscall results in the no instruction counts in output.

**Comment by ipeitzsch** [comment]
Were you running it with -n or --max_instructions?

**Comment by weiwenzhou** [comment]
I tried ```python sbumips.py test.asm -i``` and ```python sbumips.py test.asm --disp_instr_count```.

**Comment by ipeitzsch** [comment]
This was caused by an error in the implementations of syscall 10, where we would simply call `exit()`. A fix where the instruction count is printed before exiting has been made and will be pushed after further testing.
