### ISSUE TITLE
-g breaks syscall

### ISSUE THREAD

**Issue by weiwenzhou** [sbustars/STARS#3]
OS: Windows
Ran in: Git Bash and Windows Powershell

Running ``` python sbumips.py test.asm -g``` results in "InvalidSyscall: Not a valid syscall code"

**Comment by law-lin** [comment]
OS: Windows
Env: Powershell

I'm also able to reproduce this.

**Comment by ipeitzsch** [comment]
This issue was caused by an error in how registers were initialized. All registers were being randomized, when there is a subset of registers that are always 0 at the start. A fix has been made and will be pushed after further testing.
