### ISSUE TITLE
Invalid Immediate on 'andi'

### ISSUE THREAD

**Issue by wangzilezhang** [sbustars/STARS#6]
When I tried to execute the lines:

li $t0, 999
andi $a0, $t0, 100

It gave the error, "InvalidImmediate: Immediate is not unsigned 16 bit". This includes any other positive number I tested for the immediate. 

Upon further testing, I found that all negative values doesn't give me the error even though it does for MARs. 

The same code in MARs successfully resulted in the value in $a0 being "100". 

I am running STARS on CMD and I am using a windows 10 64-bit operating system

![Capture](https://user-images.githubusercontent.com/84553019/119074967-fc6ea800-b9bd-11eb-94f9-d6a852e2d57d.PNG)

**Comment by ipeitzsch** [comment]
It seems there was a logical issue where STARS raised an exception for valid immediates and didn't for invalid ones. This has now been fixed and pushed.

Thank you for your help with testing!
