### ISSUE TITLE
Doesn't support negative division?

### ISSUE THREAD

**Issue by chrissuda** [sbustars/STARS#7]
`.text
.globl main
main:
li $t0,-3
li $t1,-2
div $t0,$t1

mflo $a0
li $v0,1
syscall
mfhi $a0
li $v0,1
syscall`

The above code basically does $t0/$t1, and prints out its quotient and remainder respectively. 

In Mars, it prints out 1-1, and the # of instruction counts is 10.
In sbumips, it prints out 0-3, and the # of instruction counts is 12.

Upon further testing, as long as there are negatives involved, it won't print out the correct result. 
For example, -3/2($t0=-3,$t1=2) will prints out 21474836461. And the # of instruction counts is 11. (In Mars, it's -1-1, and the instruction count is still 10)

But if the dividend and divisor are all non-negative, it gives out the correct result and correct instruction count(which is 10)

**Comment by chrissuda** [comment]
I am using windows 10. I run it with -g -i -w

**Comment by ipeitzsch** [comment]
Just push a fix. There was a logical issue with when to do signed vs unsigned division.

For the instruction count difference, STARS uses a different pseudo instruction mapping than MARS does, which is causing the discrepancy. However, this won't affect execution or anything else.

Thank you for your help with testing!
