### ISSUE TITLE
Cannot save files created in program

### ISSUE THREAD

**Issue by mapang02** [sbustars/STARS#8]
Operating system: Linux (Ubuntu, which is run on a virtual machine on Windows)
Python version: 3.8.10, with numpy 1.19.3 and pyside 5.14.0

Files created via the program's New button cannot be saved. Pressing the Save button will show an option to choose the save location, but nothing will be saved there (and the * indicated that it isn't saved doesn't go away). Attempting to press Assemble after doing this will give the error message `IsADirectoryError: [Errno 21] Is a directory: '/'`. 

Opening, saving edits to, and assembling pre-existing .asm files (such as the examples) does not seem to have any problems. I am opening .asm files from the same folder I am trying to save to, so there shouldn't be any permissions issues.

(If it matters, I originally accidentally installed pyside 5.15.2 because I thought it would be okay. I uninstalled it and installed 5.14.0 later. This error occurred with both versions.)

**Comment by weiwenzhou** [comment]
Fixed in the update.
